### ISSUE TITLE
Core-foundation-sys shouldn't have changed version at all

### ISSUE THREAD

**Issue by tomaka** [servo/core-foundation-rs#96]
Because its Cargo.toml contains a `links` attribute, it is impossible to use `core-foundation-sys v0.2` and `core-foundation-sys v0.3` in the same project.

There is absolutely no reason why the version of `core-foundation-sys` should match the version of `core-foundation`.

**Comment by tomaka** [comment]
It's too late now anyway, but it's a heads up for the next time.
I'm tired of fixing semver issues all the time. Now I have decided to report breakages to library owners.

**Comment by tomaka** [comment]
Hopefully the 24 people who watch this repo will be aware of this and will reject a PR that bumps `core-foundation-sys`.

**Comment by nox** [comment]
I am not sure why you employ such a tone to convey your annoyance, and this is not a "semver issue". While it seems this could have been 0.2.4, doing a breaking bump doesn't break semver.

I assume you are fed up because of https://github.com/tomaka/glutin/issues/853, but this wouldn't have happened if glutin had said `core-foundation = "0.2.3"` and not `core-foundation = "0"`. Just make sure to reject a PR that depends on crates with a `"0"` version constraint.

**Comment by tomaka** [comment]
@nox It has nothing to do with that but with the `links` attribute in the Cargo.toml.

**Comment by nox** [comment]
No, core-foundation 0.3 was selected by Cargo in glutin only because Cargo does weird stuff with a single digit `"0"` version. Had both winit and core-graphics said `0.2`, none of them would have used `0.3` and no two different versions of core-foundation would have been used at the same time.

**Comment by tomaka** [comment]
I'm not talking about glutin's breakage here. It's totally glutin's fault and my fault for accepting a PR in the past that did `= "0"`.

I'm opening this because we can't bump to core-foundation 0.3 without causing breakages in the entire ecosystem.
